import type { Airport, Destination } from "./types";

export const AIRPORTS: Airport[] = [
  {
    code: "PAR",
    city: "Paris",
    name: "Tous les aéroports",
    latitude: 48.8566,
    longitude: 2.3522,
  },
  {
    code: "CDG",
    city: "Paris",
    name: "Charles de Gaulle",
    latitude: 49.0097,
    longitude: 2.5479,
  },
  {
    code: "ORY",
    city: "Paris",
    name: "Orly",
    latitude: 48.7262,
    longitude: 2.3652,
  },
  {
    code: "BOD",
    city: "Bordeaux",
    name: "Mérignac",
    latitude: 44.8283,
    longitude: -0.7156,
  },
  {
    code: "LYS",
    city: "Lyon",
    name: "Saint-Exupéry",
    latitude: 45.7256,
    longitude: 5.0811,
  },
  {
    code: "MRS",
    city: "Marseille",
    name: "Provence",
    latitude: 43.4393,
    longitude: 5.2214,
  },
  {
    code: "NTE",
    city: "Nantes",
    name: "Atlantique",
    latitude: 47.1532,
    longitude: -1.6107,
  },
  {
    code: "NCE",
    city: "Nice",
    name: "Côte d’Azur",
    latitude: 43.6584,
    longitude: 7.2159,
  },
  {
    code: "TLS",
    city: "Toulouse",
    name: "Blagnac",
    latitude: 43.6291,
    longitude: 1.3638,
  },
  {
    code: "BIQ",
    city: "Biarritz",
    name: "Pays Basque",
    latitude: 43.4684,
    longitude: -1.5233,
  },
  {
    code: "GVA",
    city: "Genève",
    name: "Genève Aéroport",
    latitude: 46.2381,
    longitude: 6.1089,
  },
  {
    code: "BRU",
    city: "Bruxelles",
    name: "Brussels Airport",
    latitude: 50.901,
    longitude: 4.4856,
  },
];

// Fixture isolée : remplacer le repository, conserver les composants et leurs contrats.
// Les indications surf sont illustratives ; elles ne constituent pas un bulletin de conditions.
export const DEMO_DESTINATIONS: Destination[] = [
  {
    slug: "ericeira",
    name: "Ericeira",
    country: "Portugal",
    countryCode: "PT",
    region: "Europe",
    coordinates: "38.963° N · 9.417° W",
    latitude: 38.963,
    longitude: -9.417,
    image: "/images/ericeira.jpg",
    imageAlt:
      "Surfeurs et lignes de houle sur une plage d’Ericeira au coucher du soleil",
    tagline: "L’Atlantique, à portée de planche.",
    description:
      "Des falaises dorées, des ruelles blanches et l’océan à chaque détour. Autour d’Ericeira, les spots se succèdent et les ambiances changent. Le bon choix dépend de ton niveau et de la houle du jour.",
    levels: ["Débutant", "Intermédiaire", "Expert"],
    recommendedLevel: "Intermédiaire",
    bestMonths: [4, 5, 6, 9, 10],
    shoulderMonths: [3, 7, 8, 11],
    airport: {
      code: "LIS",
      city: "Lisbonne",
      name: "Humberto Delgado",
      latitude: 38.7742,
      longitude: -9.1342,
    },
    transferMinutes: 45,
    spotCount: 8,
    wave: "Beach breaks & point breaks",
    bottom: "Sable et roche selon le spot",
    caution:
      "Rochers, courants et houle parfois puissante. Choisir son spot avec un surfeur local et vérifier les conditions du jour.",
    spots: [
      { name: "Foz do Lizandro", level: "Débutant", type: "Beach break" },
      { name: "São Julião", level: "Intermédiaire", type: "Beach break" },
      { name: "Coxos", level: "Expert", type: "Reef break" },
    ],
  },
  {
    slug: "taghazout",
    name: "Taghazout",
    country: "Maroc",
    countryCode: "MA",
    region: "Afrique",
    coordinates: "30.545° N · 9.709° W",
    latitude: 30.545,
    longitude: -9.709,
    image: "/images/taghazout.jpg",
    imageAlt: "Maisons de Taghazout ouvertes sur l’océan Atlantique au Maroc",
    tagline: "Les longues droites, les journées qui s’étirent.",
    description:
      "Au nord d’Agadir, la côte déroule ses pointes et ses longues plages. On vient pour les droites, on reste pour les fins de journée face à l’océan. Des premières mousses aux point breaks, chaque session a son adresse.",
    levels: ["Débutant", "Intermédiaire", "Expert"],
    recommendedLevel: "Tous niveaux",
    bestMonths: [1, 2, 3, 10, 11, 12],
    shoulderMonths: [4, 5, 9],
    airport: {
      code: "AGA",
      city: "Agadir",
      name: "Al Massira",
      latitude: 30.325,
      longitude: -9.4131,
    },
    transferMinutes: 50,
    spotCount: 12,
    wave: "Longues droites & beach breaks",
    bottom: "Sable et roche selon le spot",
    caution:
      "Respecter les priorités et les surfeurs locaux. Les pointes rocheuses demandent une bonne lecture de l’océan.",
    spots: [
      { name: "Panoramas", level: "Débutant", type: "Beach break" },
      { name: "Banana Point", level: "Intermédiaire", type: "Point break" },
      { name: "Anchor Point", level: "Expert", type: "Point break" },
    ],
  },
  {
    slug: "canggu",
    name: "Canggu",
    country: "Indonésie",
    countryCode: "ID",
    region: "Asie",
    coordinates: "8.647° S · 115.138° E",
    latitude: -8.647,
    longitude: 115.138,
    image: "/images/canggu.jpg",
    imageAlt:
      "Surfeurs sur une vague de Canggu à Bali, dans la lumière dorée du soir",
    tagline: "Une autre latitude. Le même appel de l’océan.",
    description:
      "À Bali, les matins commencent tôt, une planche sous le bras. Canggu rassemble plusieurs ambiances de surf, des vagues accessibles aux sections plus rapides. Le spot, la marée et la taille de la houle font toute la différence.",
    levels: ["Débutant", "Intermédiaire", "Expert"],
    recommendedLevel: "Intermédiaire",
    bestMonths: [5, 6, 7, 8, 9],
    shoulderMonths: [3, 4, 10],
    airport: {
      code: "DPS",
      city: "Denpasar",
      name: "Ngurah Rai",
      latitude: -8.7482,
      longitude: 115.1672,
    },
    transferMinutes: 60,
    spotCount: 6,
    wave: "Beach breaks & reef breaks",
    bottom: "Sable et récif volcanique",
    caution:
      "Trafic dense sur la route, fréquentation dans l’eau et récifs peu profonds à marée basse. Se renseigner localement avant la session.",
    spots: [
      { name: "Batu Bolong", level: "Débutant", type: "Reef break" },
      { name: "Berawa", level: "Intermédiaire", type: "Beach break" },
      { name: "Echo Beach", level: "Expert", type: "Reef break" },
    ],
  },
];
